# Generated by Django 3.0 on 2020-07-12 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_group_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256)),
                ('display_name', models.CharField(max_length=256)),
                ('email_address', models.EmailField(max_length=256)),
                ('password', models.CharField(max_length=256)),
                ('user_group_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.UserGroup')),
            ],
        ),
    ]
