# Generated by Django 3.0 on 2020-07-14 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('content', models.CharField(max_length=10000)),
                ('like_count', models.IntegerField()),
                ('created_on', models.DateTimeField()),
                ('last_updated', models.DateTimeField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.User')),
            ],
        ),
        migrations.CreateModel(
            name='BlogPostVisibility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visibility_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='BlogPostTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50)),
                ('blog_post_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.BlogPost')),
            ],
        ),
        migrations.CreateModel(
            name='BlogPostComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=5000)),
                ('created_on', models.DateTimeField()),
                ('blog_post_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.BlogPost')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.User')),
            ],
        ),
        migrations.AddField(
            model_name='blogpost',
            name='visibility_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.BlogPostVisibility'),
        ),
    ]
