# Generated by Django 3.0 on 2020-07-25 10:38

from django.db import migrations
from ..models import Tool

def createTools(apps, schema_editor):
    zoom = Tool(name="Zoom", category="Communication")
    zoom.save()

    webcms3 = Tool(name="WebCMS 3", category="Course Administration")
    webcms3.save()

    moodle = Tool(name="Moodle", category="Course Administration")
    moodle.save()

    openLearning = Tool(name="Open Learning", category="MOOC Platform")
    openLearning.save()

    webcms2 = Tool(name="WebCMS 2", category="Course Administration")
    webcms2.save()

    slack = Tool(name="Slack", category="Communication")
    slack.save()

    teams = Tool(name="teams", category="Course Administration")
    teams.save()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200722_1122'),
    ]

    operations = [
        migrations.RunPython(createTools),
    ]
