# Generated by Django 3.0 on 2020-07-22 11:38

from django.db import migrations
from django.contrib.auth.models import UserManager
from django.contrib.auth.models import User

def create_super_user(apps, schema_editor):
    # UserManager.create_superuser('admin',
    #                              password='password')
    user = User.objects.create_superuser('admin', password='password')
    user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200722_1122'),
    ]

    operations = [
        migrations.RunPython(create_super_user)
    ]
