# Generated by Django 3.0 on 2020-08-02 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200726_0006'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestBlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, max_length=160000, null=True)),
            ],
        ),
    ]
