# Generated by Django 3.0 on 2020-08-05 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200726_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='created_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
