# Generated by Django 3.0 on 2020-08-08 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200805_2121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='created_by',
            new_name='createdBy',
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='created_on',
            new_name='createdOn',
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='last_updated',
            new_name='lastUpdated',
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='like_count',
            new_name='likeCount',
        ),
    ]
