# Generated by Django 3.0 on 2020-08-11 09:16

from django.db import migrations
from django.contrib.auth.models import User
import datetime
import pytz

def createUsers(apps, schema_editor):
    '''Creates default users'''

    tz_AU = pytz.timezone('Australia/Sydney')

    userA_data = {
        'username': 'morty',
        'password': 'AdminPassword',
        'email': 'morty@cse.unsw.edu.au',
        'first_name': 'Mortada',
        'last_name': 'Al-Banna',
        'last_login': datetime.datetime.now(tz_AU)
    }

    userB_data = {
        'username': 'boualem',
        'password': 'AdminPassword',
        'email': 'boualem@cse.unsw.edu.au',
        'first_name': 'Boualem',
        'last_name': 'Bentallah',
        'last_login': datetime.datetime.now(tz_AU)
    }

    userC_data = {
        'username': 'jdoe',
        'password': 'AdminPassword',
        'email': 'jdoe@cse.unsw.edu.au',
        'first_name': 'John',
        'last_name': 'Doe',
        'last_login': datetime.datetime.now(tz_AU)
    }

    userA = User.objects.create_user(**userA_data)
    userA.save()

    userB = User.objects.create_user(**userB_data)
    userB.save()

    userC = User.objects.create_user(**userC_data)
    userC.save()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20200810_1228'),
    ]

    operations = [
        migrations.RunPython(createUsers),
    ]
