version: "3"
services:
  db:
    image: postgres:12.3
    restart: always
    environment:
      - POSTGRES_DB=toolbox
      - POSTGRES_USER=app_user
      - POSTGRES_PASSWORD=app_password
    ports:
      - 5432:5432
    volumes:
      - .backend/db/:/docker-entrypoint-initdb.d/

  backend:
     build: ./backend/.
     ports:
       - 8000:8000
     volumes:
       - ./backend/:/code
     environment:
       - DB_HOST=db
       - DB_NAME=toolbox
       - DB_USER=app_user
       - DB_PASS=app_password
     depends_on:
       - db
     command: bash -c "sleep 5
            && python manage.py makemigrations
            && python manage.py migrate
            && python manage.py runserver 0.0.0.0:8000"

  app:
    container_name: app
    tty: true
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - './app/:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true


