version: "3"
services:
  db:
    image: postgres:12.3
    restart: always
    environment:
      - POSTGRES_DB=toolbox
      - POSTGRES_USER=app_user
      - POSTGRES_PASSWORD=app_password
    ports:
      - 5432:5432
    volumes:
      - .backend/db/:/docker-entrypoint-initdb.d/

  backend:
     build: ./backend/.
     ports:
       - 8000:8000
     volumes:
       - ./backend/:/code
     environment:
       - DB_HOST=db
       - DB_NAME=toolbox
       - DB_USER=app_user
       - DB_PASS=app_password
     depends_on:
       - db
     command: bash -c "sleep 5
            && python manage.py makemigrations
            && python manage.py migrate
            && python manage.py runserver 0.0.0.0:8000"

  elastic:
    image: elasticsearch:7.8.0
    environment:
    - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300
    depends_on:
      - db

#  kibana:
#    image: docker.elastic.co/kibana/kibana-oss:6.3.2
#    ports:
#      - 5601:5601
#    environment:
#      SERVER_NAME: localhost
#      ELASTICSEARCH_URL: http://elasticsearch:9200/
#    depends_on:
#    - elastic

